In [1]:
#Créer un nouveau Notebook dans lequel vous chargez la bibliothèque numpy. 
import numpy as np

In [5]:
#Créez à partir d’une liste un array unidimensionnel et vérifiez sa taille et ce qu’il comporte.
mon_array=np.array([1,2,4,6])
print mon_array
print mon_array.shape
print mon_array.dtype

[1 2 4 6]
(4L,)
int32


In [8]:
#Générez des arrays remplis de 0 et de 1 de taille 10.
zero_array=np.zeros(10)
one_array=np.ones(10)
print zero_array,one_array

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.] [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [12]:
#Créez un array bidimensionnel avec des valeurs quelconques, calculer le cube de cet array
mon_array=np.array([[1,2,4],[1,2,3],[1,2,5]])
print mon_array**3

[[  1   8  64]
 [  1   8  27]
 [  1   8 125]]


In [17]:
#Générer un array avec des valeurs entre 0 et 8, afficher les éléments 1 à 6 
#puis modifiez les élément 6 à 8 en leur fixant la valeur de 22.

mon_array=np.array(range(9))
print mon_array[1:7]
mon_array[7:9]=22
print mon_array


[1 2 3 4 5 6]
[ 0  1  2  3  4  5  6 22 22]


In [35]:
#Construire une matrice rectangulaire de taille 3 x 2 avec une suite de nombres commençant à 5, calculer le produit de la transposée par la matrice.
mat1=np.arange(5,11).reshape((3,2))
print np.dot(mat1.T,mat1)


[[155 176]
 [176 200]]


In [47]:
#Générer un array de nombres aléatoires puis remplacer les valeurs plus petites que 0 par 0. Trier l’array obtenu

mat1 =np.random.randn(9)
print mat1
mat2=np.where(mat1>0,mat1,0)
print np.sort(mat2)

[ 0.2685868   0.95628636  0.13698128  0.7102122  -1.65516037  0.9285421
 -0.7671004   1.53821393  1.58420486]
[ 0.          0.          0.13698128  0.2685868   0.7102122   0.9285421
  0.95628636  1.53821393  1.58420486]


In [49]:
#Générer un array de nombres aléatoires tirés d’une loi normale et en calculer l’exponentielle
mat1 =np.random.randn(9)
print np.exp(mat1)

[ 0.33883133  1.55429944  1.22138069  0.64163717  0.33368793  1.05906189
  1.09302931  2.83397916  0.93731308]


In [54]:
#Générer une matrice simple et sauvegarder cette matrice dans array.npy puis dans array.txt
mat1=np.arange(9).reshape(3,3)

np.save("ma_mat.npy",mat1)
np.savetxt('ma_mat.txt', mat1, delimiter=';')